LOCAL_PATH:= $(call my-dir)
include $(CLEAR_VARS)
LOCAL_MODULE_TAGS := eng
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE:=devregs_imx6q.dat
LOCAL_MODULE_PATH := $(TARGET_OUT)/etc
LOCAL_SRC_FILES=$(LOCAL_MODULE)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE_TAGS := eng
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE:=devregs_imx6dls.dat
LOCAL_MODULE_PATH := $(TARGET_OUT)/etc
LOCAL_SRC_FILES=$(LOCAL_MODULE)
include $(BUILD_PREBUILT)

