LOCAL_PATH:= $(call my-dir)
LOCAL_MODULE_TAGS := eng
LOCAL_SRC_FILES:=devregs.cpp
LOCAL_MODULE:=devregs
LOCAL_CPPFLAGS += -DANDROID
LOCAL_SHARED_LIBRARIES:=libc
LOCAL_C_INCLUDES += $(LOCAL_PATH)
include $(BUILD_EXECUTABLE)

include $(CLEAR_VARS)

